### ISSUE TITLE
Failed to establish a new connection

### ISSUE THREAD

**Issue by MeteorVE** [frozenpandaman/s3s#119]
Error Log

```
$ python s3s.py -M -r
s3s v0.3.4
Validating your tokens...

The stored tokens have expired.
Attempting to generate new gtoken and bulletToken...
Wrote tokens for MeteorV to config.txt.

Checking if there are previously-unuploaded battles/jobs...
Previously-unuploaded battles detected. Uploading now...
Battle already uploaded - https://stat.ink/@MeteorV/spl3/f14359d1-3d26-4447-99dc-6b38098704e0
No previously-unuploaded jobs found.

Waiting for new battles/jobs... (checking every 5 minutes)

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Python38\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Python38\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "C:\Python38\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001FF95DCD3A0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.lp1.av5ja.srv.nintendo.net', port=443): Max retries exceeded with url: /api/graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FF95DCD3A0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "s3s.py", line 2000, in <module>
    main()
  File "s3s.py", line 1968, in main
    check_if_missing(which, blackout, test_run, skipprefetch) # monitoring mode hasn't begun yet
  File "s3s.py", line 1432, in check_if_missing
    fetch_and_upload_single_result(id, noun, isblackout, istestrun)
  File "s3s.py", line 1343, in fetch_and_upload_single_result
    result_post = requests.post(utils.GRAPHQL_URL,
  File "C:\Python38\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.lp1.av5ja.srv.nintendo.net', port=443): Max retries exceeded with url: /api/graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FF95DCD3A0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

```

**Comment by frozenpandaman** [comment]
This is an issue on your end with your internet. Just try running the script again.
