### ISSUE TITLE
failed to generate token

### ISSUE THREAD

**Issue by dogwong** [frozenpandaman/s3s#138]
```
s3s v0.5.2
Validating your tokens...

The stored tokens have expired.
Attempting to generate new gtoken and bulletToken...
Traceback (most recent call last):
  File "C:\s3s\MT\s3s.py", line 2047, in <module>
    main()
  File "C:\s3s\MT\s3s.py", line 2013, in main
    prefetch_checks(printout=True)
  File "C:\s3s\MT\s3s.py", line 130, in prefetch_checks
    gen_new_tokens("expiry")
  File "C:\s3s\MT\s3s.py", line 171, in gen_new_tokens
    new_gtoken, acc_name, acc_lang, acc_country = iksm.get_gtoken(F_GEN_URL, SESSION_TOKEN, A_VERSION)
  File "C:\s3s\MT\iksm.py", line 234, in get_gtoken
    id_response = json.loads(r.text)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by timeimp** [comment]
Getting the exact same error message.

Only started today.

**Comment by timeimp** [comment]
Seems to be working again.

I'm guessing some server maintenence got in the way of everything running.

I'd try again @dogwong !

**Comment by dogwong** [comment]
@timeimp my one is now working also

**Comment by frozenpandaman** [comment]
Hmm, I should handle this error at least and have it print a better error message rather than crashing... will get it fixed later.

**Comment by frozenpandaman** [comment]
I've improved JSON error handling in a bunch of places in `iskm.py` now, as of 88929ad. No version bump because there's no new features, really, and this rarely happens.

Thanks for the report!
