### ISSUE TITLE
Running Problem

### ISSUE THREAD

**Issue by Doggiekong** [frozenpandaman/s3s#149]
Hi, frozenpandaman

I installed s3s sucsessfully, also run sucessfully. The battle information have been uploaded to stat.ink on the first day.
But after that day, it won't run well anymore. It shows the following feedback. What happen to me, and how to fix it? Thank you very much!

```
_Traceback (most recent call last):
  File "/Users/doggie/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/doggie/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/doggie/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/doggie/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/doggie/miniconda3/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/doggie/miniconda3/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/doggie/miniconda3/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/doggie/miniconda3/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Users/doggie/miniconda3/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/doggie/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/doggie/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/doggie/miniconda3/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.lp1.av5ja.srv.nintendo.net', port=443): Max retries exceeded with url: /static/js/main.01625c4e.js (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/doggie/s3s/s3s.py", line 2077, in <module>
    main()
  File "/Users/doggie/s3s/s3s.py", line 2043, in main
    prefetch_checks(printout=True)
  File "/Users/doggie/s3s/s3s.py", line 120, in prefetch_checks
    iksm.get_web_view_ver() # setup
  File "/Users/doggie/s3s/iksm.py", line 105, in get_web_view_ver
    main_js_body = requests.get(main_js_url, headers=app_head, cookies=app_cookies)
  File "/Users/doggie/miniconda3/lib/python3.10/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/doggie/miniconda3/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/doggie/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/doggie/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/doggie/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.lp1.av5ja.srv.nintendo.net', port=443): Max retries exceeded with url: /static/js/main.01625c4e.js (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))_
```

**Comment by timeimp** [comment]
I got a similar error message about `Response closed remotely` but it only appears to happen when NOT in debug mode?

I will test further but have noticed this happen more since 5.1.0

**Comment by Twister2849** [comment]
I’m not 100% sure but I think you have to do something along the lines of installing modules like `pip install pyopenssl`

**Comment by frozenpandaman** [comment]
@Doggiekong Anaconda isn't the recommended method of installing Python so I can't help with errors in that area, if you've chosen to set up your environment using that distribution. To me, this looks like a problem with your internet connection – but I'm pretty sure that it's not an error on s3s' end.
