### ISSUE TITLE
Catch error while SplatNet 3 is undergoing maintenance

### ISSUE THREAD

**Issue by frozenpandaman** [frozenpandaman/s3s#88]
```
Got non-JSON response from Nintendo (in api/bullet_tokens step):
Traceback (most recent call last):
  File "/Users/adr/s3s/iksm.py", line 394, in get_bullet
    bullet_resp = json.loads(r.text)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adr/s3s/s3s.py", line 1781, in <module>
    main()
  File "/Users/adr/s3s/s3s.py", line 1747, in main
    prefetch_checks(printout=True)
  File "/Users/adr/s3s/s3s.py", line 130, in prefetch_checks
    gen_new_tokens("expiry")
  File "/Users/adr/s3s/s3s.py", line 172, in gen_new_tokens
    new_bullettoken = iksm.get_bullet(new_gtoken, APP_USER_AGENT, acc_lang, acc_country)
  File "/Users/adr/s3s/iksm.py", line 398, in get_bullet
    print(bullet_resp)
UnboundLocalError: local variable 'bullet_resp' referenced before assignment
```

**Comment by frozenpandaman** [comment]
Fixed in ed218d8. Also made it so gtokens still successfully get written to `config.txt` even during maintenance.

cc @Adrthegamedev
